:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
:schedule:
  mark_cart_as_abandoned:
    cron: "0 * * * *"  # Roda a cada 1 hora
    class: "MarkCartAsAbandonedJob"
